#pragma once

#include <string>
#include <vector>

std::vector<std::string> symbolCodes = {"clearsky",
                                        "clearsky_day",
                                        "cloudy",
                                        "fair",
                                        "fog",
                                        "heavyrain",
                                        "heavyrainandthunder",
                                        "heavyrainshowers",
                                        "heavyrainshowersandthunder",
                                        "heavysleet",
                                        "heavysleetandthunder",
                                        "heavysleetshowers",
                                        "heavysleetshowersandthunder",
                                        "heavysnow",
                                        "heavysnowandthunder",
                                        "heavysnowshowers",
                                        "heavysnowshowersandthunder",
                                        "lightrain",
                                        "lightrainandthunder",
                                        "lightrainshowers",
                                        "lightrainshowersandthunder",
                                        "lightsleet",
                                        "lightsleetandthunder",
                                        "lightsleetshowers",
                                        "lightsnow",
                                        "lightsnowandthunder",
                                        "lightsnowshowers",
                                        "lightssleetshowersandthunder",
                                        "lightssnowshowersandthunder",
                                        "partlycloudy",
                                        "partlycloudy_day",
                                        "rain",
                                        "rainandthunder",
                                        "rainshowers",
                                        "rainshowersandthunder",
                                        "sleet",
                                        "sleetandthunder",
                                        "sleetshowers",
                                        "sleetshowersandthunder",
                                        "snow",
                                        "snowandthunder",
                                        "snowshowers",
                                        "snowshowersandthunder"};

std::vector<std::string> symbolCorrections = {"Clear sky",
                                              "Clear sky",
                                              "Cloudy",
                                              "Fair",
                                              "Fog",
                                              "Heavy rain",
                                              "Heavy rain and thunder",
                                              "Heavy rain showers",
                                              "Heavy rain showers and thunder",
                                              "Heavy sleet",
                                              "Heavy sleet and thunder",
                                              "Heavy sleet showers",
                                              "Heavy sleet showers and thunder",
                                              "Heavy snow",
                                              "Heavy snow and thunder",
                                              "Heavy snow showers",
                                              "Heavy snow showers and thunder",
                                              "Light rain",
                                              "Light rain and thunder",
                                              "Light rain showers",
                                              "Light rain showers and thunder",
                                              "Light sleet",
                                              "Light sleet and thunder",
                                              "Light sleet showers",
                                              "Light snow",
                                              "Light snow and thunder",
                                              "Light snow showers",
                                              "Light sleet showers and thunder",
                                              "Light snow showers and thunder",
                                              "Partly cloudy",
                                              "Partly cloudy",
                                              "Rain",
                                              "Rain and thunder",
                                              "Rain showers",
                                              "Rain showers and thunder",
                                              "Sleet",
                                              "Sleet and thunder",
                                              "Sleet showers",
                                              "Sleet showers and thunder",
                                              "Snow",
                                              "Snow and thunder",
                                              "Snow showers",
                                              "Snow showers and thunder"};